# Generated by Django 3.0.8 on 2020-07-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200703_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='aliasname',
            options={'verbose_name_plural': '别名'},
        ),
        migrations.AlterModelOptions(
            name='alipay',
            options={'verbose_name_plural': '支付宝'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name_plural': '职业'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': '邮件'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': '人员'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': '电话号码'},
        ),
        migrations.AlterModelOptions(
            name='qnum',
            options={'verbose_name_plural': 'QQ'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='wechat',
            options={'verbose_name_plural': '微信'},
        ),
        migrations.AlterModelOptions(
            name='weibo',
            options={'verbose_name_plural': '微博'},
        ),
    ]
