# Generated by Django 3.0.8 on 2020-07-04 18:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
