# Generated by Django 3.0.8 on 2020-07-05 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20200704_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xianyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='闲鱼')),
                ('primary_use', models.BooleanField(default=False, verbose_name='是否主要使用')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name_plural': '闲鱼',
            },
        ),
        migrations.CreateModel(
            name='Douyin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='抖音')),
                ('primary_use', models.BooleanField(default=False, verbose_name='是否主要使用')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name_plural': '抖音',
            },
        ),
    ]
