# Generated by Django 3.0.8 on 2020-07-06 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_douyin_xianyu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xianyu',
            options={'verbose_name_plural': '闲鱼淘宝旺旺'},
        ),
        migrations.AlterField(
            model_name='xianyu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='闲鱼/淘宝/旺旺'),
        ),
        migrations.CreateModel(
            name='OtherAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='其他账号')),
                ('primary_use', models.BooleanField(default=False, verbose_name='是否主要使用')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name_plural': '其他账号',
            },
        ),
        migrations.CreateModel(
            name='Baidu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='百度')),
                ('primary_use', models.BooleanField(default=False, verbose_name='是否主要使用')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name_plural': '百度',
            },
        ),
    ]
